sudo: required
services:
  - docker

before_install:
  - docker build -t lxmondragon/docker-react -f Dockerfile.dev .

script:
  - docker run lxmondragon/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk